name=MAX30001
version=1.4.0
author=Urs Utzinger
maintainer=Urs Utzinger
sentence=Library for the MAXIM 30001G sensor
paragraph=Driver for the MAX30001G AFE, which is a single-lead ECG and BIOZ AFE with integrated ADC and DSP for wearable applications.
category=Sensors
url=https://github.com/uutzinger/Arduino_MAX30001G
architectures=*
includes=max30001g.h
depends=UUtzinger_RingBuffer, UUtzinger_logger
