name=MAX30001
version=1.0.0
author=Urs Utzinger
maintainer=Urs Utinger
sentence=Library for the MAXIM 30001 sensor
paragraph=Enables you to use the MAX30001
url=https://github.com/uutzinger/MAX30001
category=Sensors
includes=max30001g.h
