name=Arduino_MAX30001G
version=1.0.4
author=Urs Utzinger
maintainer=Urs Utzinger
sentence=Library for the MAXIM 30001G sensor
paragraph=Driver for the MAX30001G AFE, which is a single-lead ECG and BIOZ AFE with integrated ADC and DSP for wearable applications.
url=https://github.com/uutzinger/Arduino_MAX30001G
category=Sensors
includes=max30001g.h
depends=UUtzinger_RingBuffer, UUtzinger_logger
